// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "get_all_users", input: never, result: string } | 
        { key: "version", input: never, result: string },
    mutations: never,
    subscriptions: never
};
