// This file was generated by [rspc](https://github.com/oscartbeaumont/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "get_current_user", input: never, result: string } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "update_system", input: never, result: string } | 
        { key: "upgrade_system", input: never, result: string },
    subscriptions: never
};
