#!/bin/bash

RED='\e[0;31m' #red color
NC='\e[0m' # no color
GREEN='\e[0;32m' # green

COMMIT_REGEX='^(feat|fix|docs|style|refactor|test|chore)(\(.+\))?: .{1,90}$'

if ! grep -E "$COMMIT_REGEX" "$1"; then
  echo -e "${RED}Aborting commita. Your commit message is invalid.${NC}"
  echo -e "    -> You have to use Conventional Commit Convensions."
  exit 1
fi
