name: "Test"

on:
  pull_request:
    paths:
      - pnpm-lock.yaml
      - src/**
      - src-tauri/**
      - .github/workflows/**

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install frontend dependencies
        run: pnpm install
      - name: lint frontend
        run: pnpm lint
      - name: format check frontend
        run: pnpm format:check

  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: Run sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.3
      - name: install platform dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: lint backend
        run: |
          cd src-tauri
          cargo clippy -- -D warnings
      - name: format check backend
        run: |
          cd src-tauri
          cargo fmt -- --check
